/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    private LinkedList head;
    public LinkedList list;
    private LinkedList tail;

    public static void main(String[] args) {
        new App().run(args);
        return;
    }

    public String run(String [] args)
    {

        boolean exiter = false;
        String input_file_path = args[0],
              output_file_path = args[1],
              transform_name = args[2];
      Bitmap cryptoPunk = new Bitmap(input_file_path, output_file_path);
                 //"src/main/resources/baldy-8bit.bmp", "src/main/resources/cryptopunk.bmp");
        //do{

        switch(transform_name)
        {
            case("random"):  cryptoPunk.randomizer(); break;
            case("invert"): cryptoPunk.invert(); break;
            case("grey"): cryptoPunk.greyScale(); break;
            default:
                cryptoPunk.reset();
                exiter = true;
                break;
        }
        if(!exiter) cryptoPunk.writeOutImage();
        //}while(ask());
        //history(transform_name);
    return "success!";
    }
    public boolean ask()
    {
        System.out.println("do you want to continue? yes(y) or no(n)");
        Scanner user = new Scanner(System.in);
        String userInput = user.next();
        userInput = userInput.toLowerCase();
        if(userInput.equals("yes") || userInput.equals("y")){return true;}
        return false;
    }
    public void displayAllHistory(LinkedList head)
    {
        if(head == null) return ;
        System.out.println(head.getData() + "->" + head.getNext() != null? head.getNext():"null");
        displayAllHistory(head.getNext());
        return;
    }
    //1. read to cachetxt
    public boolean readCache()
    {
        boolean success = false;
        try{
            CacheReader historyReader = new CacheReader("src/main/resources/cache.txt");
            historyReader.readCache();
            success = true;
        }
        catch(FileNotFoundException e)
        {
            e.printStackTrace();
            System.exit(-1);
        }
        return success;
    }
    //2. write to cachetxt
    public void writeCache()
    {
        try{
            CacheWriter historyWriter = new CacheWriter("src/main/resources/cache.txt");
            historyWriter.writeCache(list);
            System.exit(0);
        }
        catch(FileNotFoundException e)
        {
            e.printStackTrace();
            System.exit(-1);
        }
    }
    //3. add to cachetxt
    public void history(String data)
    {
        if(list == null){
            this.list = new LinkedList(data);
            this.head = this.tail = list;
            return;
        }
        LinkedList temp = new LinkedList(data);
        temp.setNext(list.getNext());
        list.setNext(temp);
        list = list.getNext();
        tail = list;
    }
/* BufferedImage image = new BufferedImage();
            BMP pic = BufferedImage.class.getClassLoader().getResource("baldy-8bit.bmp");
            BufferedImage icon = new BufferedImage(pic);
            PLabel label = new PLabel(icon);
            frame.add(label);
            frame.setDefaultCloseOperation
                    (Plabel.EXIT_ON_CLOSE);
            FRAME.pack();
            FRAME.setVisible(true);
            */
}




