/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new App().run(args);
        return;
    }

    public String run(String [] args)
    {

        boolean exiter = false;
        String input_file_path = args[0],
              output_file_path = args[1],
              transform_name = args[2];
      Bitmap cryptoPunk = new Bitmap(input_file_path, output_file_path);
                 //"src/main/resources/baldy-8bit.bmp", "src/main/resources/cryptopunk.bmp");
        //do{

        switch(transform_name)
        {
            case("random"):  cryptoPunk.randomizer(); break;
            case("invert"): cryptoPunk.invert(); break;
            case("grey"): cryptoPunk.greyScale(); break;
            default:
                cryptoPunk.reset();
                exiter = true;
                break;
        }
        if(!exiter) cryptoPunk.writeOutImage();
        //}while(ask());
    return "success!";
    }
    public boolean ask()
    {
        System.out.println("do you want to continue? yes(y) or no(n)");
        Scanner user = new Scanner(System.in);
        String userInput = user.next();
        userInput = userInput.toLowerCase();
        if(userInput.equals("yes") || userInput.equals("y")){return true;}
        return false;
    }
/* BufferedImage image = new BufferedImage();
            BMP pic = BufferedImage.class.getClassLoader().getResource("baldy-8bit.bmp");
            BufferedImage icon = new BufferedImage(pic);
            PLabel label = new PLabel(icon);
            frame.add(label);
            frame.setDefaultCloseOperation
                    (Plabel.EXIT_ON_CLOSE);
            FRAME.pack();
            FRAME.setVisible(true);
            */
}




